"""
Django settings for insta project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from .defaults import DEFAULT_HEADERS
# from corsheaders.defaults import default_headers
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!euyr1(%9(!z=#dju4dl7mqg1_268*1_r6g1sx=&u@^^c0ccsc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS=['*']




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'products',
    'account',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_HEADERS = DEFAULT_HEADERS 


# DEFAULT_HEADERS = list(default_headers) + [
#     "WWW-Authenticate",
#     "Authorization",
#     "Proxy-Authenticate",
#     "Proxy-Authorization",
#     "Age",
#     "Cache-Control",
#     "Clear-Site-Data",
#     "Expires",
#     "Pragma",
#     "Warning",
#     "Accept-CH",
#     "Accept-CH-Lifetime",
#     "Sec-CH-UA",
#     "Sec-CH-UA-Arch",
#     "Sec-CH-UA-Bitness",
#     "Sec-CH-UA-Full-Version",
#     "Sec-CH-UA-Full-Version-List",
#     "Sec-CH-UA-Mobile",
#     "Sec-CH-UA-Model",
#     "Sec-CH-UA-Platform",
#     "Sec-CH-UA-Platform-Version",
#     "Content-DPR",
#     "Device-Memory",
#     "DPR",
#     "Viewport-Width",
#     "Width",
#     "Downlink",
#     "ECT",
#     "RTT",
#     "Save-Data",
#     "Last-Modified",
#     "ETag",
#     "If-Match",
#     "If-None-Match",
#     "If-Modified-Since",
#     "If-Unmodified-Since",
#     "Vary",
#     "Connection",
#     "Keep-Alive",
#     "Accept",
#     "Accept-Encoding",
#     "Accept-Language",
#     "Expect",
#     "Max-Forwards",
#     "Cookie",
#     "Set-Cookie",
#     "Access-Control-Allow-Origin",
#     "Access-Control-Allow-Credentials",
#     "Access-Control-Allow-Headers",
#     "Access-Control-Allow-Methods",
#     "Access-Control-Expose-Headers",
#     "Access-Control-Max-Age",
#     "Access-Control-Request-Headers",
#     "Access-Control-Request-Method",
#     "Origin",
#     "Timing-Allow-Origin",
#     "Content-Disposition",
#     "Content-Length",
#     "Content-Type",
#     "Content-Encoding",
#     "Content-Language",
#     "Content-Location",
#     "Forwarded",
#     "X-Forwarded-For",
#     "X-Forwarded-Host",
#     "X-Forwarded-Proto",
#     "Via",
#     "Location",
#     "From",
#     "Host",
#     "Referer",
#     "Referrer-Policy",
#     "User-Agent",
#     "Allow",
#     "Server",
#     "Accept-Ranges",
#     "Range",
#     "If-Range",
#     "Content-Range",
#     "Cross-Origin-Embedder-Policy",
#     "Cross-Origin-Opener-Policy",
#     "Cross-Origin-Resource-Policy",
#     "Content-Security-Policy",
#     "Content-Security-Policy-Report-Only",
#     "Expect-CT",
#     "Feature-Policy",
#     "Origin-Isolation",
#     "Strict-Transport-Security",
#     "Upgrade-Insecure-Requests",
#     "X-Content-Type-Options",
#     "X-Download-Options",
#     "X-Frame-Options",
#     "X-Permitted-Cross-Domain-Policies",
#     "X-Powered-By",
#     "X-XSS-Protection",
#     "Sec-Fetch-Site",
#     "Sec-Fetch-Mode",
#     "Sec-Fetch-User",
#     "Sec-Fetch-Dest",
#     "Service-Worker-Navigation-Preload",
#     "Last-Event-ID",
#     "NEL",
#     "Ping-From",
#     "Ping-To",
#     "Report-To",
#     "Transfer-Encoding",
#     "TE",
#     "Trailer",
#     "Sec-WebSocket-Key",
#     "Sec-WebSocket-Extensions",
#     "Sec-WebSocket-Accept",
#     "Sec-WebSocket-Protocol",
#     "Sec-WebSocket-Version",
#     "Accept-Push-Policy",
#     "Accept-Signature",
#     "Alt-Svc",
#     "Date",
#     "Early-Data",
#     "Large-Allocation",
#     "Link",
#     "Push-Policy",
#     "Retry-After",
#     "Signature",
#     "Signed-Headers",
#     "Server-Timing",
#     "Service-Worker-Allowed",
#     "SourceMap",
#     "Upgrade",
#     "X-DNS-Prefetch-Control",
#     "X-Firefox-Spdy",
#     "X-Pingback",
#     "X-Requested-With",
#     "X-Robots-Tag",
#     "X-UA-Compatible",
#     "ContentType",
#     "Content-type",
#     "content-type",
#     "contenttype",
#     "contentType",


#     "accept",
#     "authorization",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",

#     "accept-encoding",

#     "Contentype",
# ]




ROOT_URLCONF = 'insta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'insta.wsgi.application'

AUTH_USER_MODEL = 'account.User'
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
